
//This file has been automatcally generated by pngconverter utility
//Please do not edit
#ifndef LOGO2_H
#define LOGO2_H

#include "mxgui/image.h"

extern const mxgui::Image logo2;

#endif //LOGO2_H
